const types = {
  FETCH_POSTS: "FETCH_POSTS",
  ADD_POST: "ADD_POST",
  SELECTED_LOCATION: "SELECTED_LOCATION",
  LOGIN: "LOGIN",
  LOGIN_LOADING: "LOGIN_LOADING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERROR: "REGISTER_ERROR",
  REGISTER_LOADING: "REGISTER_LOADING",
  FETCH_REQUESTS: "FETCH_REQUESTS",
  ADD_FRIEND: "ADD_FRIEND",
  DECLINE_REQUEST: "DECLINE_REQUEST",
  TAGS_CHANGE: "TAGS_CHANGE",
  NEW_PHOTO_TAG: "NEW_PHOTO_TAG",
  USERS_CHANGE: "USERS_CHANGE",
};

export default types;
