const types = {
  FETCH_POSTS: "FETCH_POSTS",
  ADD_POST: "ADD_POST",
  SELECTED_LOCATION: "SELECTED_LOCATION",
  LOGIN: "LOGIN",
  LOGIN_LOADING: "LOGIN_LOADING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERROR: "REGISTER_ERROR",
  REGISTER_LOADING: "REGISTER_LOADING",
  ADD_LIKE: "ADD_LIKE",
  FILTER_LOADING: "FILTER_LOADING",
  FILTER_SUCCESS: "FILTER_SUCCESS",
  FILTER_ERROR: "FILTER_ERROR"
};

export default types;
